on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Render and Deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Create Git LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      - name: Check out Git LFS content
        run: git lfs checkout

      - name: Setup TeX Live
        uses: zauguin/install-texlive@v4
        with:
          packages: scheme-full

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to web server
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
